"""urvish1

Revision ID: 39df2bb4c96d
Revises: 
Create Date: 2024-06-05 15:52:02.441538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39df2bb4c96d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('F_name', sa.String(length=20), nullable=False),
    sa.Column('L_name', sa.String(length=20), nullable=False),
    sa.Column('Course', sa.String(length=20), nullable=False),
    sa.Column('Mobile_No', sa.String(length=10), nullable=False),
    sa.Column('Email', sa.String(length=30), nullable=False),
    sa.Column('Date_of_Birth', sa.String(length=20), nullable=False),
    sa.Column('Place_of_Birth', sa.String(length=20), nullable=False),
    sa.Column('Gender', sa.String(length=20), nullable=False),
    sa.Column('University_name', sa.String(length=20), nullable=False),
    sa.Column('HSC_Result', sa.String(length=20), nullable=False),
    sa.Column('HSC_Passing_year', sa.String(length=20), nullable=False),
    sa.Column('HSC_School_name', sa.String(length=20), nullable=False),
    sa.Column('Aadhaarcard_num', sa.String(length=12), nullable=False),
    sa.Column('Father_business', sa.String(length=20), nullable=False),
    sa.Column('Father_income', sa.String(length=20), nullable=False),
    sa.Column('Hobbies', sa.String(length=30), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
